[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = req_ext

[dn]
C=BR
ST=RJ
L=Rio de Janeiro
O=DevOps
OU=Teste                            # mudar para sua OU
CN=portainer.teste.local            # mudar para seu CN

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = portainer.teste.local       # mudar para o seu DNS
IP.1 = 123.123.123.123              # mudar para o seu IP
